### ISSUE TITLE
loadstring() is not working.

### ISSUE THREAD

**Issue by TannerRogalsky** [gamesys/moonshine#14]
Running `loadstring("print('test')")()` results in a web request to /print('test').

There seems to be a bug in the test suite which may have caused this to have been overlooked: https://github.com/gamesys/moonshine/blob/master/test/scripts/lib.lua#L139

That line generates a web request to /test/lib-loadfile.lua which 404s.

**Comment by xcombelle** [comment]
I just played with your product and it is fantastic.

However I would like to reopen this issue.

This behavior is incompatible with standard lua. One  solution could be to rename the present loadstring in something like loadbytecode and define loadstring with something like:

    function loadstring(s)
        return loadbytecode(string.dump(s))
    end

**Comment by paulcuth** [comment]
Hi @xcombelle, I'm no longer working on the Moonshine team and as far as I know it's pretty dormant. If you'd like to use `loadstring()` you may like to try out [Starlight](http://starlight.paulcuth.me.uk) that executes Lua code, rather than bytecode.
