### ISSUE TITLE
move license to something more permissive

### ISSUE THREAD

**Issue by seanjensengrey** [gamesys/moonshine#26]
LGPL, Apache or MIT. LGPL would be great.

**Comment by paulcuth** [comment]
Fixed in a310947a9b1207a076ecf437ec58ede88323edde.

Thank you all for helping me push this through, it's very much appreciated. Enjoy!

**Comment by seanjensengrey** [comment]
Oh wow! Thanks Paul. I'll port some Lua Love trinkets over to http://impactjs.com/ejecta and http://tannerrogalsky.com/punchdrunk/ and post a gist on it. 

Great news everyone!
