### ISSUE TITLE
can I use moonshine with node.js?

### ISSUE THREAD

**Issue by bofeng** [gamesys/moonshine#28]
In your guide page you showed use shell command to compile lua code to a json-for-bytecode file, like this:

``` bash
moonshine distil hello.lua
```

 I am wondering is there any API I could use to do the same thing in node.js ? maybe something like:

``` javascript
var shine = require('vm/moonshine.js');
var jsonForByteCode = shine.distil("print 'hello'");
```

Thanks.

**Comment by paulcuth** [comment]
I'm guessing you won't need this anymore, but for those that are still arriving here via search engines, the functionality that was missing here in Moonshine is now the basis of the Starlight project (which shares standard library code with Moonshine):

http://starlight.paulcuth.me.uk
