### ISSUE TITLE
init.lua not loaded

### ISSUE THREAD

**Issue by premek** [gamesys/moonshine#34]
I found this issue with https://github.com/TannerRogalsky/punchdrunk which is using moonshine.
Looks like moonshine is not trying to load `init.lua` from a folder that is `require`d.

`require "foldername"`

I think it should try to load `foldername.lua` etc but also `foldername/init.lua`'

In lua it is configurable but default can be found here: http://www.lua.org/source/5.1/luaconf.h.html

- https://github.com/TannerRogalsky/punchdrunk/issues/55
- https://github.com/TannerRogalsky/punchdrunk/issues/57

**Comment by paulcuth** [comment]
You'll need to update the value of `package.path` in Moonshine. It's uses different paths to C Lua by default. I should document this somewhere.

Try:
```lua
package.path = '?/init.lua.js;'..package.path
```

**Comment by premek** [comment]
Thanks
