### ISSUE TITLE
Support for Lua modules

### ISSUE THREAD

**Issue by darmie** [gamesys/moonshine#36]
Hi there, I want to use moonshine in a project and I need to know if I  import a Lua module within a Lua script, will it work?

**Comment by paulcuth** [comment]
If the module is entirely written in Lua and has no external dependencies, yes. 

See https://github.com/gamesys/moonshine/blob/master/test/scripts/lib-require.lua for an example of how to create a module and also how to require another.

**Comment by darmie** [comment]
Thank you

**Comment by darmie** [comment]
Before I close this issue, I want to ask if it's possible to update Lua scripts dynamically at runtime using Moonshine?

**Comment by paulcuth** [comment]
Unfortunately not. Moonshine runs the Lua bytecode and therefore any Lua scripts first need to be compiled.

However, you may be interested in my other project, Starlight, which translates Lua script to ES6 and is therefore able to run arbitrary code dynamically at runtime:
https://github.com/paulcuth/starlight

Let me know if you have any further issues.

**Comment by darmie** [comment]
Thank you, seems like starlight is what I need.
